### ISSUE TITLE
Add some Simple Game Codes 

### ISSUE THREAD

**Issue by AbhilashaGupta16** [AbhilashaGupta16/HacktoberFest-#5]

**Comment by yashqwerty1** [comment]
can you assign me this task.

**Comment by Ansh04122001** [comment]
can i add  snake game in python

**Comment by AbhilashaGupta16** [comment]
Yes , both of u can add your files.

**Comment by satcasm** [comment]
@AbhilashaGupta16 I had added a simple color guessing game yesterday. Please review it.

**Comment by hambali999** [comment]
Hi can you assigned me to this task, i am willing to add some games!

**Comment by AbhilashaGupta16** [comment]
Open to all, anyone can contribute here.

**Comment by satcasm** [comment]
@AbhilashaGupta16 please review my PR. #22

**Comment by aritrochakraborty29** [comment]
I want to add some cool games here..
